### ISSUE TITLE
Look into service workers

### ISSUE THREAD

**Issue by JohnMcLear** [ether/ep_offline_edit#5]
https://github.com/slightlyoff/ServiceWorker/

**Comment by petrk94** [comment]
@JohnMcLear is this still on work?
The Plugin doesnt got updated in the last 6 years. I dont want to say its dead, but I really would like to get Service Worker running, especially, because Appcache has problems and the plugin is not documented where the appcache is located or how to edit it.
Thanks

**Comment by JohnMcLear** [comment]
@petrk94 [Sorry, but no.](https://mclear.co.uk/2016/08/17/farewell-etherpad/)

**Comment by petrk94** [comment]
@JohnMcLear 
Oh I understand now. Alright, I will check whether someone can check that or whether I can fix it by my own. I just began to learn javascript, so I will give it a try and maybe I can help someone else with it.
Thanks anyway for your work on etherpad :)
